overwrite: true
schema: ${NEXT_PUBLIC_BACKEND_URL}
documents: "./src/gql/queries.ts"
generates:
  ./src/gql/generated.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-graphql-request"
  ./graphql.schema.json:
    plugins:
      - "introspection"
